project_id = "jqthuwrklpuiiucfeozn"

[functions.place-order]
verify_jwt = true

[functions.update-order-status]
verify_jwt = true

[functions.fetch-recommendations]
verify_jwt = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.chat-support]
verify_jwt = true

[functions.analytics]
verify_jwt = true

[functions.setup-admin]
verify_jwt = true

[functions.admin-analytics]
verify_jwt = true

[functions.vendor-analytics]
verify_jwt = true
